/* eslint-disable import/prefer-default-export */

export const ACTION_DB_LOAD = 'DB_LOAD';
export const ACTION_DB_LOAD_SUCCESS = 'DB_LOAD_SUCCESS';
export const ACTION_DB_SAVE = 'DB_SAVE';
export const ACTION_DB_DELETE = 'DB_DELETE';
export const ACTION_DB_SEED = 'DB_SEED';
export const ACTION_DB_SEED_SUCCESS = 'DB_SEED_SUCCESS';
export const ACTION_DB_CLEAR = 'DB_CLEAR';
export const ACTION_DB_PERSIST = 'DB_PERSIST';

export const ACTION_API_ERROR = 'API_ERROR';
export const ACTION_APPLICATION_SEND_MESSAGE = 'APPLICATION_SEND_MESSAGE';

export const ACTION_MERCHANTS_LOAD = 'MERCHANTS_LOAD';
export const ACTION_MERCHANTS_LOAD_SUCCESS = 'MERCHANTS_LOAD_SUCCESS';
export const ACTION_MERCHANTS_LOAD_ERROR = 'MERCHANTS_LOAD_ERROR';
export const ACTION_MERCHANT_SAVE = 'MERCHANT_SAVE';
export const ACTION_MERCHANT_SAVE_SUCCESS = 'MERCHANT_SAVE_SUCCESS';
export const ACTION_MERCHANT_SAVE_ERROR = 'MERCHANT_SAVE_ERROR';
export const ACTION_MERCHANT_DESTROY = 'MERCHANT_DESTROY';
export const ACTION_MERCHANT_DESTROY_SUCCESS = 'MERCHANT_DESTROY_SUCCESS';
export const ACTION_MERCHANT_DESTROY_ERROR = 'MERCHANT_DESTROY_ERROR';

export const ACTION_BIDS_LOAD = 'BIDS_LOAD';
export const ACTION_BIDS_LOAD_SUCCESS = 'BIDS_LOAD_SUCCESS';
export const ACTION_BIDS_LOAD_ERROR = 'BIDS_LOAD_ERROR';
export const ACTION_BID_SAVE = 'BID_SAVE';
export const ACTION_BID_SAVE_SUCCESS = 'BID_SAVE_SUCCESS';
export const ACTION_BID_SAVE_ERROR = 'BID_SAVE_ERROR';
export const ACTION_BID_DESTROY = 'BID_DESTROY';
export const ACTION_BID_DESTROY_SUCCESS = 'BID_DESTROY_SUCCESS';
export const ACTION_BID_DESTROY_ERROR = 'BID_DESTROY_ERROR';

export const HTTP_STATUS_UNPROCESSABLE_ENTITY = 422;
